name: Maven CI/CD

on:
  push:
    branches: [ci-git]

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - name: Step 1 -Checkout main branch from GitHub
      uses: actions/checkout@v2

    - name: Step 2- Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Step 3- Build project with Maven
      run: mvn -B package --file pom.xml

    - name: Step 4 - Generate JaCoCo Badge
      id: jacoco
      uses: cicirello/jacoco-badge-generator@v2.7.0
      with:
        badges-directory: .github/badges
        generate-coverage-badge: true
        coverage-badge-filename: jacoco.svg
        generate-branches-badge: false
        branches-badge-filename: branches.svg

    - name: Step 5 - Log coverage percentage
      run: |
        echo "coverage = ${{ steps.jacoco.outputs.coverage }}"
        echo "branch coverage = ${{ steps.jacoco.outputs.branches }}"  

    - name: Step 6 - Upload JaCoCo coverage report
      uses: actions/upload-artifact@v2
      with:
        name: jacoco-report
        path: target/site/jacoco/

#    - name: Step 7 - Commit badge
#      uses: EndBug/add-and-commit@v7
#      with:
#        default_author: github_actions
#        message: 'commit badge'
#        add: '*.svg'
#
#    - name: Step 8 -  Push badge commit
#      uses: ad-m/github-push-action@master
#      with:
#        github_token: ${{ secrets.GITHUB_TOKEN }}
#        branch: ${{ steps.extract_branch.outputs.branch }}